### ISSUE TITLE
Nyxx#version returns an old version

### ISSUE THREAD

**Issue by HarryET** [nyxx-discord/nyxx#165]
**Describe the bug**
Nyxx#version returns an old version

**To Reproduce**

Print value `Nyxx#version`

**Expected behavior**

Print current version

**Screenshots**
N/a

**Desktop (please complete the following information):**
N/a
 - OS: [e.g. Windows, Linux]
 - Dart version [e.g. 2.9.0]
 - Nyxx version [e.g. 1.0.0]

**Additional context**

Maybe CI could change this?
Could use pubspec?
Add to PR template to update?

**Comment by l7ssha** [comment]
There is no simple way of doing that without parsing pubspec? Which requires addtional package.

Will fix on 2.0.0 release

**Comment by l7ssha** [comment]
Will be fixed in #183
