### ISSUE TITLE
Interactions return `dynamic` instead of `InteractionOption?`

### ISSUE THREAD

**Issue by HarryET** [nyxx-discord/nyxx#185]
**Describe the bug**
SlashCommandInteraction.getArgs return dynamic but the options(args) are actually Iterable<InteractionOption> so it should be InteractionOption?

**To Reproduce**
```dart
event.interaction.getArg('count')
```

**Expected behavior**
return typed value or InteractionOption

**Screenshots**
N/a

**Desktop (please complete the following information):**
- OS: Linux
- Dart version: 2.13
- Nyxx version: 2.0.0-rc.13

**Additional context**
```dart
  /// Args of the interaction
  late final Iterable<InteractionOption> options;
```
```dart
  /// Allows to fetch argument value by argument name
  dynamic getArg(String name) {
    try {
      return this.options.firstWhere((element) => element.name == name);
    } on Error {
      return null;
    }
  }
  ```

**Comment by l7ssha** [comment]
getArg should return matching `InteractionOption`'s value not `InteractionOption` itself
