### ISSUE TITLE
Failed to connect to lavalink

### ISSUE THREAD

**Issue by BrunoMoraes-Z** [nyxx-discord/nyxx#205]
**Describe the bug**
I'm trying to create a simple music command, but when I try to connect with lavalink on the cluster, the bot can't connect.

**To Reproduce**
`await cluster.addNode(NodeOptions());`

**Expected behavior**
successful connection to node

**Screenshots**
![image](https://user-images.githubusercontent.com/54856390/134825760-df7b0bdf-a18c-45d0-8241-00499ccb00e8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Dart version: 2.13.4
 - nyxx: ^2.0.0-rc.7
 - nyxx_lavalink: ^2.0.0-rc.3

**Additional context**
https://github.com/BrunoMoraes-Z/dartcord

**Comment by HarryET** [comment]
Alvaro wrote the Lavalink module. I have CCed them and they should hopefully be able to help!

//cc @AlvaroMS25

**Comment by AlvaroMS25** [comment]
Seems like the host is refusing the connection, are you running lavalink server? If yes, are you providing the correct credentials to the cluster?

**Comment by BrunoMoraes-Z** [comment]
I'm trying to run on my machine even on vscode, One thing I saw some people report is that it could be the port, I'll test it soon

**Comment by AlvaroMS25** [comment]
If this doesn't fix the issue you should update to the latest version of lavalink jar, i personally recommend to download it directly from the CI at [here](https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1) or directly from its [repository](https://github.com/freyacodes/Lavalink)'s releases

**Comment by BrunoMoraes-Z** [comment]
I was able to successfully connect to Lavalink, the version you are using is incorrect.
