### ISSUE TITLE
Slash commands do not register / update on Discord

### ISSUE THREAD

**Issue by vxern** [nyxx-discord/nyxx#213]
**Describe the bug**
I have used `Interactions.registerSlashCommand()` and a sample slash command to register it, but the slash commands on my server do not update / refresh. The additions have worked once or twice, but very unpredictably. Restarting Discord and the bot did not help at all.

**To Reproduce**
Use `Interactions.registerSlashCommand()` attempting to add different commands.

**Expected behavior**
The slash commands I have removed should have disappeared, and the ones I have added should have appeared. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version: 2.15.0-51.0.dev
 - Nyxx version: 2.0.0-rc.15

**Comment by l7ssha** [comment]
https://github.com/nyxx-discord/nyxx/blob/dev/nyxx_interactions/example/basic.dart#L38-L41

You need to call `syncOnReady` in order to sync commands to discord api

**Comment by vxern** [comment]
> https://github.com/nyxx-discord/nyxx/blob/dev/nyxx_interactions/example/basic.dart#L38-L41
> 
> You need to call `syncOnReady` in order to sync commands to discord api

Yes, I do call `Interactions.syncOnReady` after trying to add slash commands.

**Comment by l7ssha** [comment]
if commands are global then yes, because discord caches them for one hour. Post command line output and sample code if problem persists, because Im not able to provide further help without those.

**Comment by vxern** [comment]
Thank you for the information.
