### ISSUE TITLE
Non-nullable Types

### ISSUE THREAD

**Issue by teaishealthy** [nyxx-discord/nyxx#232]
**Describe the bug**
A few embed attribute types are nullable although they should not be, which then requires the some null check.

##### EmbedAuthor.name
https://github.com/nyxx-discord/nyxx/blob/24d45b97631f62a878d4d4e65e27ac163351d51d/nyxx/lib/src/core/embed/EmbedAuthor.dart#L6 [Documentation]( https://discord.com/developers/docs/resources/channel#embed-object-embed-author-structure)

##### EmbedFooter.text
https://github.com/nyxx-discord/nyxx/blob/24d45b97631f62a878d4d4e65e27ac163351d51d/nyxx/lib/src/core/embed/EmbedFooter.dart#L6 [Documentation](https://discord.com/developers/docs/resources/channel#embed-object-embed-footer-structure)

##### EmbedThumbnail.url
https://github.com/nyxx-discord/nyxx/blob/24d45b97631f62a878d4d4e65e27ac163351d51d/nyxx/lib/src/core/embed/EmbedThumbnail.dart#L6 [Documentation](https://discord.com/developers/docs/resources/channel#embed-object-embed-thumbnail-structure)

**To Reproduce**
```dart
foo(embed.author.name!); // requires a null assertion
bar(embed.footer.text ?? ""); // or a null-aware operator
```

**Expected behavior**
The attributes should be non-nullable and not require any null checks.

**Desktop:**
 - OS: Windows 11, WSL Ubuntu
 - dart:  2.14.0-188.5.beta
 - nyxx: 2.1.0

**Comment by l7ssha** [comment]
Fixed on `next` branch
