### ISSUE TITLE
Implement missing ActivityTypes

### ISSUE THREAD

**Issue by HarryET** [nyxx-discord/nyxx#275]
- https://discord.com/developers/docs/topics/gateway#activity-object-activity-types

`ActivityType` 3 is missing, it should be set to watching. Also need to check if this is used in other files e.g. `PresenceBuilder`
https://github.com/nyxx-discord/nyxx/blob/dev/lib/src/core/user/presence.dart#L265

**Comment by 61soldiers** [comment]
🙋
