### ISSUE TITLE
Unusual behaviour of IMessage#edit

### ISSUE THREAD

**Issue by vanxh** [nyxx-discord/nyxx#282]
if u replied to a message with embeds in it and then you do IMessage#edit and do embeds an empty list. it dont removed the embed from message.

**Comment by vanxh** [comment]
j

**Comment by abitofevrything** [comment]
It seems that the MessageBuilder `build()` does not attach an embeds array in its payload if it is empty.

**Comment by vanxh** [comment]
> 

yes thats it
