### ISSUE TITLE
Invalid Date Format error when fetching a guild member

### ISSUE THREAD

**Issue by HIHIQY1** [nyxx-discord/nyxx#330]
**Describe the bug**
I'm getting an Invalid Date Format error when trying to fetch a guild member.

Stacktrace:
```
DateTime.parse (dart:core/date_time.dart:347)
DateTime.tryParse (dart:core/date_time.dart:358)
new Member (c:\Users\Qy\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\nyxx-3.4.1\lib\src\core\user\member.dart:189)
HttpEndpoints.fetchGuildMember (c:\Users\Qy\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\nyxx-3.4.1\lib\src\internal\http_endpoints.dart:769)
<asynchronous gap> (Unknown Source:0)
handleVoiceStateUpdate (c:\Users\Qy\Documents\.....\main.dart:25)
<asynchronous gap> (Unknown Source:0)
```
Seems to be originating from parsing `premium_since`:
```Dart
    boostingSince = DateTime.tryParse(raw["premium_since"] as String? ?? "");
```

**To Reproduce**
```Dart
void main() async {
  final INyxxWebsocket bot = NyxxFactory.createNyxxWebsocket(getToken("token"), GatewayIntents.allUnprivileged)
    ..registerPlugin(Logging())
    ..registerPlugin(CliIntegration())
    ..connect();

  bot.eventsWs.onVoiceStateUpdate.listen(handleVoiceStateUpdate);
}

void handleVoiceStateUpdate(IVoiceStateUpdateEvent e) async {
  if (e.state.guild != null) {
    IMember foundMember = await (await e.state.guild!.getOrDownload()).fetchMember(e.state.user.id);
  }
}
```

**Expected behavior**
No error being thrown

**Screenshots**
none

**Desktop:**
 - OS: Windows
 - Dart version 2.16.2
 - Nyxx version 3.4.1

**Additional context**
none

**Comment by abitofevrything** [comment]
Hi,
The implementation of `DateTime.tryParse` does indeed throw an invalid date format error if the string passed is not correct, however this is caught straight away by a try-catch block. This error never propagates, so this is a non-issue.

If you are seeing this error, you probably have "break on all exceptions" set in your debugger. You very rarely want to select this, and should instead select "break on uncaught exceptions".

Closing this, please reopen if I am wrong.
