### ISSUE TITLE
Event to notify change of connection status

### ISSUE THREAD

**Issue by r3a1d3a1** [nyxx-discord/nyxx#363]
**Is your feature request related to a problem? Please describe.**
I would like to know when the bot loses connection for any reason, and when it gets back online.

**Describe the solution you'd like**
An event to subscribe to.

**Describe alternatives you've considered**
Using this hacky code for now:
```dart
class HackyLogging extends BasePlugin {
  @override
  FutureOr<void> onRegister(INyxx nyxx, logg.Logger logger) {
    logg.Logger.root.onRecord.listen((logg.LogRecord rec) {
      //TODO: Need to keep an eye on 
      // https://github.com/nyxx-discord/nyxx/blob/dev/lib/src/internal/shard/shard.dart#L221
      // in case the string changes even slightly!
      if( rec.message.startsWith("Not received previous heartbeat ack") ){
        print("Oh no!!!");
      } else if( rec.message.contains("connected to gateway") ){
        // Catch up with all the stuff since we were last online...
      }
      print("[${rec.time}] [${rec.level.name}] [${rec.loggerName}] ${rec.message}");
    });
  }
}

.
.
.

bot!.registerPlugin(HackyLogging());
```

**Comment by l7ssha** [comment]
Prefered solution would be adding proper hook in BasePlugin. Adding this feature requst to 4.1 milestone :)

**Comment by r3a1d3a1** [comment]
Hi Szymon,
I looked at the code changes in the [two related commits](https://github.com/nyxx-discord/nyxx/pull/364/files) and couldn't figure out whether it notifies a successful reconnection as well. Does it?!
Also, just found out about _onDisconnect_ & _onResume_  events. Is there an advantage to using a plugin then?
Maybe a simple demo example would be helpful.
Thank you 🙏

**Comment by r3a1d3a1** [comment]
Hey man,
Here are a few different scenarios I've encountered:

- [SHOUT] [Shard Manager] Shard 0 reported error: Connection timed out
- [SHOUT] [Shard Manager] Shard 0 reported error: Network is unreachable
- [SHOUT] [Shard Manager] Shard 0 reported error: Connection reset by peer

I still have to rely on my HackyLogging class for catching them. How does you PR in #363 and #364 help with these?!

**Comment by abitofevrything** [comment]
All of these scenarios can be handled from onConnectionError in a plugin.

Create a class that extends `BasePlugin` and override the `onConnectionError` method. This is where you handle the error. Then, just add your plugin to your client with `client.registerPlugin(MyPlugin())`.

**Comment by r3a1d3a1** [comment]
Sorry, but that's not much better than the hack I'm already using.
It relies on _String errorMessage_ which potential values could easily change from one release to the next, w/o the developer noticing.
Instead, it should rely on an enum, so as not only to provide stability, but also transparency into all possible cases.

**Comment by abitofevrything** [comment]
This is a good idea, but it would be a breaking change so it will have to wait until the next major version of nyxx, and we won't be able to provide any more information than the type of error.

Until then, you'll have to deal with with just the message - the event isn't really intended for much more than logging or metrics and can change without notice due to it being linked to the internal shard implementation simply requesting an error when needed.

As of now, here is a list of all possible messages:
- `Shard is already connected` - shard was requested to connect to the Gateway when it was already connected
- `Unhanded exception $err` - unexpected exception when connecting to the Gateway
- `Shard is already reconnecting` - shard was requested to reconnect while already reconnecting
- `Cannot disconnect shard if no connection is active` - shard was requested to disconnect while already disconnected
- `Cannot send data when connection is closed` - shard was requested to send data with no active connection
- (others) - `WebSocketException` or `SocketException` message

**Comment by r3a1d3a1** [comment]
Thank you for considering this.

As the title suggests, I'd really appreciate it if the case of a successful connection -after zero or more failed attempts- is also in the **enum**. I edited the example in my first post to reflect this (acting on string "connected to gateway").
(Current _onReady_ event fires only initially, not after a reconnect.)

I imagine in that case, from a naming perspective, instead of _onConnectionError_, it'd be best to have an _onConnectionChange_ method to override.

The **enum** values could be: 
- (Re)Connecting
- Connected
- Disconnected (not reconnecting)

In the case of Reconnecting or Disconnected, a secondary **enum** could be provided for the reason.

P.S. Implementing _onConnectionChange_ anew would also have the benefit of not being a breaking change; and _onConnectionError_ could be deprecated in the next major version if not providing any additional utility.

**Comment by abitofevrything** [comment]
Have you seen [`client.shardManager.onConnected`](https://pub.dev/documentation/nyxx/latest/nyxx/IShardManager/onConnected.html) and [`client.shardManager.onDisconnect`](https://pub.dev/documentation/nyxx/latest/nyxx/IShardManager/onDisconnect.html)? Which events get emitted where isn't very consistent as there are many cases to cover, but there is a place for everything.

They don't give details why the shard has disconnected but these give you what you want.

As for the disconnected (not reconnecting) case, this will only happen in two cases:
- Unrecoverable errors, which results in your bot crashing
- Bot disposal, which only happens after you trigger it - either through CliIntegration or `client.dispose()`

**Comment by r3a1d3a1** [comment]
Thank you.
I tried the two streams mentioned, plus the _onResume_ stream, but didn't get anything for a successful reconnection.

**Comment by abitofevrything** [comment]
Hmm. After closer inspection, there is indeed an issue - onConnected is not triggered when it should be, which is a bug. This will be fixed soon.

`onResume` is triggered after a succesful *resume*, which is a bit more complicated than just reconnecting - a shard can reconnect without resuming, for example.

**Comment by r3a1d3a1** [comment]
I thought it was agreed that having enums instead of strings would be a good idea. Too much work? :)

**Comment by abitofevrything** [comment]
No, not for connection status. For that, listening to the different connection streams is preferred.

An enum to indicate failure reason will be added in the next major version. If you want to open an issue to track that, feel free to do so.

**Comment by abitofevrything** [comment]
Yes. It would be a breaking change, because Dart does not support overloading.

Even if Dart did support overloading it would wait until the next major version as having to support overloaded methods means calling two seperate methods everywhere... which isn't really maintanable.

**Comment by r3a1d3a1** [comment]
Btw, in regards to [this](https://github.com/nyxx-discord/nyxx/issues/363#issuecomment-1295366560), `onDisconnect` never happens when Discord suddenly can't be reached. I suppose it should be emitted within [this block](https://github.com/nyxx-discord/nyxx/blob/59f41a1932ed56a1b5557109a0c9944fc13dea3c/lib/src/internal/shard/shard.dart#L295) as well?
However, it'd need to be emitted only once, not after each unsuccessful retry attempt(, or it'll have to get its own name, like `onFailedReconnect`).

**Comment by r3a1d3a1** [comment]
I remember getting "Shard 0 reported error: Connection timed out" and "Shard 0 reported error: Network is unreachable" errors when connected to WiFi with **no** internet, but not getting any `onDisconnect` events. 
So I should've just waited a bit more?! 🤔

**Comment by abitofevrything** [comment]
Well, unless you were connected previously, no disconnection happens - only connection errors.

**Comment by r3a1d3a1** [comment]
Works good! It seems like I wasn't patient enough last time :)
Btw, shouldn't `eventsWs.onDisconnect` trigger in the mentioned scenarios as well?
