### ISSUE TITLE
Add websocket reconnection backoff 

### ISSUE THREAD

**Issue by l7ssha** [nyxx-discord/nyxx#382]
Hey man, 

Please allow us to set the time in between retries.
Ideally, provide a way to set three parameters: min (const Duration), max (const Duration), and multiplier (double).
(assert that max is larger than min or if it's null, don't impose an upper limit. multiplier should be >= 1)

E.g. I'd like it to start at 15s, doubling after each failure up to 10min. (This is to save battery.)
min:15s, max:10min, multiplier:2 ===> 15s, 30s, 1min, 2min, 4min, 8min, 10min, 10min, 10min, 10min, ....

Thanks a lot!

_Originally posted by @r3a1d3a1 in https://github.com/nyxx-discord/nyxx/issues/306#issuecomment-1295186712_

**Comment by r3a1d3a1** [comment]
And obviously, once the connections succeeds, the delay should be reset to _min_ for future retries.

**Comment by r3a1d3a1** [comment]
I hope you don't mind me asking. How can I feed in a custom RetryOptions so that minDelay is 10s and maxDelay is 10min?

**Comment by r3a1d3a1** [comment]
Sorry, I meant to ask where in the code setup I feed my custom RetryOptions? CacheOptions or ClientOptions?!

**Comment by abitofevrything** [comment]
ClientOptions... Retrying has nothing to do with caching

**Comment by r3a1d3a1** [comment]
Awesome... Had to look around a bit to figure out how/where to pass it... That was the tricky part. Thank you!
