### ISSUE TITLE
feature: improve error handling

### ISSUE THREAD

**Issue by l7ssha** [nyxx-discord/nyxx#401]
**Is your feature request related to a problem? Please describe.**
sometimes error messages returned by nyxx cane be unclear and ambiguous

**Describe the solution you'd like**
Since discord returns error message with code and if request had payload: detailed info about whats wrong  with request we should be able to implement better messages using this info.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by abitofevrything** [comment]
Wrong issue. Please make sure you're on the latest version and are providing `RetryOptions` that will trigger a retry.

If you're having issues, I would recommend joining our [Discord server](https://discord.gg/nyxx) where we can actually help, as GitHub issues are not the place for that.

**Comment by r3a1d3a1** [comment]
It fit the title well, but maybe not perfectly aligned with the description of the issue :)
Anyway, it's not terribly important, but just nice to have.
