### ISSUE TITLE
Proposal: Dispatch raw event on all events

### ISSUE THREAD

**Issue by Rapougnac** [nyxx-discord/nyxx#413]
**Is your feature request related to a problem? Please describe.**

If some developer wants to deal with raw data for certain types of actions (like some data that is juggling between 2 event, 1 which is new, and the latter is already implemented but lacks of some fields, currently, only the new event would be fired on raw)

e.g:
```dart
class SuperCoolMessageBuilder extends MessageBuilder {
	bool? isCool;

	@override
	Map<String, dynamic> build() => {
		...super.build(),
		'cool': isCool ?? false,
	};
}

void main() {
	final client = ...;
	
	client.shardManager.rawEvent.listen((e) async {
		if (e['t'] == 'SOME_NEW_COOL_EVENT') {
			await client.httpEndpoints.editMessage(e['d']['channel_id'], e['d']['message_id'], SuperCoolMessageBuilder()..isCool = true);
		}
	});
			
	client.eventsWs.onMessageUpdate.listen((e) {
		// how to get the `isCool` property if it's not implemented?
		if (e.isCool) {}
	});
```
			

**Describe the solution you'd like**

At every event, dispatch the raw event, then dispatch events like we do currently.

**Describe alternatives you've considered**

Not really, maybe add a `raw` field on every event to get all data..

**Additional context**
None

**Comment by abitofevrything** [comment]
We could simply change the `dispatchRawShardEvent` option to have this behaviour. I don't think adding a `raw` field to every event is a great idea as it would just encourage people to use non-type-safe fields and hacky methods like they would in javascript for example.
