### ISSUE TITLE
Nyxx Docs Update

### ISSUE THREAD

**Issue by intfract** [nyxx-discord/nyxx#422]
It would be nice if the `nyxx` docs were a bit clearer.  I had to look at other people's code to know how to register slash commands using the `nyxx_interactions` package. 
- I added some useful code to the markdown to tell people how to sync commands 
- I reminded people to import the appropriate libraries because I almost forgot when I read the docs 
- I changed up the wording so the docs are a bit clearer 

I posted an issue here instead of [nyxx_docs](https://github.com/nyxx-discord) because I noticed no one was watching that repository. I made a pull request 14 hours ago at the time of writing this issue. 

Anyways, nice library!

**Comment by l7ssha** [comment]
https://github.com/nyxx-discord/nyxx_docs/pull/11 merged
