### ISSUE TITLE
feature: Apply tags to an already existing forum thread

### ISSUE THREAD

**Issue by phorcys420** [nyxx-discord/nyxx#424]
**Is your feature request related to a problem? Please describe.**
``ForumThreadBuilder`` expect a ``message`` argument, which means they're only for creating new threads.

**Describe the solution you'd like**
Since ``IThreadChannels`` only accept regular ThreadBuilders for ``edit()``, and you wouldn't want to let users think they can apply tags to regular threads, I think #423 has to come beforehand.
I was thinking of making ``message`` optional on ``ForumThreadBuilder``s, and to be able to feed them to the ``edit()`` method of future ``IForumThreadBuilder``s (suggestion from #423).

**Describe alternatives you've considered**
I am currently using a dirty [class extension](https://github.com/coder/codercord/blob/1e0ba367a30a44dc673e6a704a1f7ebbab4e62b7/lib/discord/utils.dart#L62) 🤮

**Comment by abitofevrything** [comment]
Need to implement actually using the builder in an edit method.

**Comment by l7ssha** [comment]
@abitofevrything is it fixed in 6.0?

**Comment by abitofevrything** [comment]
Yes. Closing now.
