### ISSUE TITLE
IForumChannel is missing webhook endpoints

### ISSUE THREAD

**Issue by CoocooFroggy** [nyxx-discord/nyxx#444]
**Describe the solution you'd like**
Forum channels have Integration -> Webhooks on Discord
https://discord.com/developers/docs/resources/webhook#get-channel-webhooks

I'm not sure how this could best be implemented, as `IForumChannel` does not implement `ITextGuildChannel` where webhooks seem to be currently implemented.

**Comment by l7ssha** [comment]
@abitofevrything is it fixed in 6.0?

**Comment by abitofevrything** [comment]
Yes, closing now.
