### ISSUE TITLE
Setting the DND Status for the User

### ISSUE THREAD

**Issue by felixkriechbaum** [nyxx-discord/nyxx#504]
Hey folks,

I have heard that it should be possible to set the DND status of the user who requested it (so for example at /changeStatus dnd).
After a long search I found several things but nothing to set. So it would be cool if you could add that.

**Comment by abitofevrything** [comment]
Hi, the way this is done is by authorising your application via oauth2 to have the `activities.write` scope. nyxx currently does not support authenticating with anything other than a bot token, so this currently isn't possible.

We are currently rewriting nyxx to add support for oauth2 which will be coming in 6.0, so I'll add this issue to that milestone. For now, you'll just have to let the user set their status via the official client.
