### ISSUE TITLE
Type cast is incorrect when using etf payload format

### ISSUE THREAD

**Issue by Rapougnac** [nyxx-discord/nyxx#558]
**Describe the bug**
Currently, an error is thrown when using etf as payload format, as snowflakes are sent as ints.

**To Reproduce**
Set the payloadFormat to etf

**Expected behavior**
Should not throw

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version 3.0.7
 - Nyxx version 6.0.0-dev.2

**Additional context**
https://github.com/nyxx-discord/nyxx/blob/363069676690b7407ed5d98ace94938b9cf08309/lib/src/http/managers/guild_manager.dart#L46
https://github.com/nyxx-discord/nyxx/blob/363069676690b7407ed5d98ace94938b9cf08309/lib/src/http/managers/sticker_manager.dart#L84
https://github.com/nyxx-discord/nyxx/blob/363069676690b7407ed5d98ace94938b9cf08309/lib/src/http/managers/sticker_manager.dart#L91
https://github.com/nyxx-discord/nyxx/blob/363069676690b7407ed5d98ace94938b9cf08309/lib/src/http/managers/sticker_manager.dart#L92
https://github.com/nyxx-discord/nyxx/blob/363069676690b7407ed5d98ace94938b9cf08309/lib/src/http/managers/emoji_manager.dart#L35

I repertoried some lines here, but we can presume other casts remains.

**Comment by abitofevrything** [comment]
Hmm. These should've all been replaced when `Snowflake.parse` was changed to take an `Object` instead of a `String` - maybe they were added back afterwards because of the habit of adding `as String`?

The fix is simple though, simply removing `as String` resolves the issue.
