### ISSUE TITLE
Music Bot

### ISSUE THREAD

**Issue by Y4CN** [nyxx-discord/nyxx#586]
Thanks for lovely package 

I wanna one big example of a join and leave bot and play something like a music in my discord bot in dart and this package
can anyone help me with that ❤️?

**Comment by abitofevrything** [comment]
Hi, thanks for your interest in nyxx!

We have a package for playing any audio, including music, in a voice channel: [`nyxx_lavalink`](https://pub.dev/packages/nyxx_lavalink). Our example bot, [Running on Dart](https://github.com/nyxx-discord/running_on_dart), uses Lavalink to enable music playing; you can see how that's implemented [here](https://github.com/nyxx-discord/running_on_dart/blob/rewrite/lib/src/services/music.dart) and [here](https://github.com/nyxx-discord/running_on_dart/blob/rewrite/lib/src/commands/music.dart).

`nyxx_lavalink` currently does not support nyxx 6.0.0, so you'll have to use nyxx 5.1.1 if you plan on using it - we're working on updating it to 6.0.0, after which we'll also update Running on Dart so you can see an up-to-date example.

If you want to try out Running on Dart, you can join [our Discord server](https://discord.gg/nyxx) where we have the bot and some voice channels for testing.

Closing this issue as the package already exists.
