### ISSUE TITLE
Documentation rework

### ISSUE THREAD

**Issue by l7ssha** [nyxx-discord/nyxx#75]
All documentation in code, as well as github wiki should rewritten to be more explanatory, examples should be included. There should be also few complete bots that can be used as example.

- [ ] In code documentation
   In code documentation should have explanation what it does with usage example where possible. 
- [ ] Github wiki
  Github wiki should be in focused on explaining specific topic and kept in convetion 'how to...'
- [x] In-repo examples
   - adding/removing role
   - adding/removing permissions 
   - kicking/banning users
   - creating/deleting channels
   - creating/deleting invites 
- [x] Complete bot as example
   - [x] Upload 'Running on Dart' code
     -  https://github.com/l7ssha/running_on_dart
   - [ ] Povide links to other bots
     - https://gitlab.com/ftl-bot/ftl

**Comment by HarryET** [comment]
This is being moved to https://github.com/nyxx-discord/nyxx_docs/issues/1
